version: '3.8'

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nestjs

  redis:
    image: redis:6
    ports:
      - '6379:6379'

volumes:
  postgres:
    name: nest-db